### ISSUE TITLE
try FastUInt32ToBufferLeft() in protobuf.

### ISSUE THREAD

**Issue by chenshuo** [miloyip/itoa-benchmark#6]
https://code.google.com/p/protobuf/source/browse/trunk/src/google/protobuf/stubs/strutil.cc#892
64-bit is also available.

**Comment by amdn** [comment]
I looked at FastUInt32ToBufferLeft() in protobuf (thanks for the pointer) and liked the performance, but not the code - so  I wrote a simpler version derived from protobuf that runs faster

https://github.com/amdn/itoa_ljust

and created a new itoa-benchmark implementation called amartin.cpp - since it is derived from protobuf, I would consider this issue closed.
